services:
  web:
    build: .
    # for localhost access
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=8086
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=sensors_db
      - BROKER_ADDRESS=host.docker.internal
      - BROKER_PORT=1883
      - CLIENT_ID=brisa-iot-web
      - CONTROL_TOPIC=brisa-iot/control
      - SENSOR_TOPIC=brisa-iot/sensors